<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<!-- Version number and accompanying SHA512 hash values for the Godot editor. -->
    <PropertyGroup>
        <GodotVersion>4.6.3</GodotVersion>
        <GodotCheckHash>true</GodotCheckHash>

        <!-- Hash values for official Godot builds are available in the SHA512-SUMS.txt file in the official release -->
        <GodotHash Condition="$(IsGodotWin64)">87e265d354f3f71971a90eab70bcb18bcaf1698686c403051c57e30d6a8478cb670e25341867e7d9b66fa1f0761c9cc38d0ae7253154a4b2b21a84b09896625f</GodotHash>
        <GodotHash Condition="$(IsGodotWinARM)">0ef69293e6d3ebb8e387bd29d0382194c377326c7328790b05b471ff53b7cd9812311c7f153aa4f3e3480965da44aa94b279920b0e1df296c7c337f3360f82d9</GodotHash>

        <GodotHash Condition="$(IsGodotOSX64)">8c4c1c83a7a3e1cfc845e0fd4b4cdefd6f1cc662f63378c22a551b50f31965f2a633b7bf7c84ab530847e0fddb5dadc1128e04e87918618dd76c75d66eb67bb9</GodotHash>
        <GodotHash Condition="$(IsGodotOSXARM)">8c4c1c83a7a3e1cfc845e0fd4b4cdefd6f1cc662f63378c22a551b50f31965f2a633b7bf7c84ab530847e0fddb5dadc1128e04e87918618dd76c75d66eb67bb9</GodotHash>

        <GodotHash Condition="$(IsGodotLinux64)">962c4f5fd3a704de36c9dedcb2f5f6c973065ac8ed8fd6e12c7ebf7e48c3852d774bcef2ccf76b50b206c0c564ceea54315e2943e76e397529923e7de680508e</GodotHash>
        <GodotHash Condition="$(IsGodotLinuxARM)">3a4471e1b596f0e45bb5386f4b8d7f44e661a4aba7d5abdca578d28e8cb499e99438abffac05bf6e7432ee56b6709fc32b4c2c2309031604ee2a5c3da1a86519</GodotHash>
    </PropertyGroup>
</Project>