<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<!-- Version number and accompanying SHA512 hash values for the Godot editor. -->
    <PropertyGroup>
        <GodotVersion>4.6</GodotVersion>
        <GodotCheckHash>true</GodotCheckHash>

        <!-- Hash values for official Godot builds are available in the SHA512-SUMS.txt file in the official release -->
        <GodotHash Condition="$(IsGodotWin64)">9d6bcc54a8eeda0035ef878072180982393e2ac4a61730d273d024649de2278e89847a9a53dbf0f10b07acfad15098b0fdbb1472862c9e73d054c666476dc096</GodotHash>
        <GodotHash Condition="$(IsGodotWinARM)">ff188065dc85dcc67c2bbee1908971ea65b8d5ac5df4f778741c29228c5e4bea5fb8249a41328ecb9ee51e598b58f7362fa65c003daa08fe78eebf2b4f5ea121</GodotHash>

        <GodotHash Condition="$(IsGodotOSX64)">85cb900331d6e2c99543b8130ad698c91508e87ec54fedef0a62c1a71b2eceb8d9ededb760109468734da0773c0a8261fda25cfe3345775b31412a944b371dad</GodotHash>
        <GodotHash Condition="$(IsGodotOSXARM)">85cb900331d6e2c99543b8130ad698c91508e87ec54fedef0a62c1a71b2eceb8d9ededb760109468734da0773c0a8261fda25cfe3345775b31412a944b371dad</GodotHash>

        <GodotHash Condition="$(IsGodotLinux64)">a132863e12fe4230eca9259dffefccaf98eeda79d05e082ebb8dd73d44a1a511181ff8f04a15bf4989fb5c91bd480fc21159b0753938c562ed85c2941c7a5777</GodotHash>
        <GodotHash Condition="$(IsGodotLinuxARM)">820d1535b5be2be3e8b4eead9747a360b521079276ae2b9f1105e7222b17b97824cb4acbea182e520ff1ab26c84cf0ad9cf739d9e22c546776aba936763ab7ff</GodotHash>
    </PropertyGroup>
</Project>